import re
from datetime import datetime
from typing import Any

import chromadb

from search_lab.embed.models import EmbedModelSpec
from search_lab.ingest.models import Chunk


def chroma_client(path: str):
    client = chromadb.PersistentClient(
    path=path
    )
    return client

def _name_tag(hf_name: str) -> str:
    # HF names like "sentence-transformers/all-MiniLM-L6-v2" -> "all-minilm-l6-v2"
    tag = hf_name.split("/")[-1].lower()
    tag = re.sub(r"[^a-z0-9]+", "-", tag).strip("-")
    return tag

def collection_name_for(store_name: str, strategy: str, hf_name: str) -> str:
    tag = _name_tag(hf_name)
    return f"{store_name}_{strategy}_{tag}"

def create_collection(client, name: str, strategy: str, hf_name: str) -> Any:
    collection = client.get_or_create_collection(
        name=collection_name_for(name, strategy, hf_name),
        embedding_function=None,
        metadata={
            "description": f"Collection for {name} embeddings generated by {strategy} chunking",
            "hf_name": hf_name,
            "created": str(datetime.now()),
        },
        configuration={"hnsw": {"space": "cosine"}},
    )
    return collection

def generate_embeddings(
    chunks: list[Chunk], embed_model_spec: EmbedModelSpec
) -> list[list[float]]:
    embeddings = embed_model_spec.model.encode(
        [chunk.text for chunk in chunks], normalize_embeddings=True
    ).tolist()
    return embeddings

def add_data(
    collection, chunks: list[Chunk], embeddings
):
    collection.upsert(
        ids=[chunk.id for chunk in chunks],
        embeddings=embeddings,
        documents=[chunk.text for chunk in chunks],
        metadatas=[
            {
                "page_number": chunk.page,
                "char_start": chunk.char_start,
                "strategy": chunk.strategy
            }
            for chunk in chunks
        ],
    )
def orchestrate_chroma_store_for_strategy(
    chunks: list[Chunk],
    embed_model_spec: EmbedModelSpec,
    strategy: str,
    store_name: str,
    db_path: str = "chroma",
) -> int:
    client = chroma_client(db_path)
    collection = create_collection(
        client, store_name, strategy, embed_model_spec.hf_name
    )
    embeddings = generate_embeddings(chunks, embed_model_spec)
    add_data(collection, chunks, embeddings)
    return collection.count()

def chunks_from_collection(collection) -> list[Chunk]:
    """Read all chunks back out of a Chroma collection as Chunk objects.

    Single source of truth: the chunks already indexed in Chroma (with their
    provenance) are reused for the OpenSearch/BM25 index, so both backends
    hold identical units.
    """
    got = collection.get(include=["documents", "metadatas"])
    return [
        Chunk(
            id=cid,
            text=doc,
            page=meta["page_number"],  # Chroma key -> Chunk.page
            char_start=meta["char_start"],
            strategy=meta["strategy"],
        )
        for cid, doc, meta in zip(got["ids"], got["documents"], got["metadatas"])
    ]